# Generated by Django 4.1.1 on 2023-04-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anns', '0002_alter_ann_department_alter_ann_end_alter_ann_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ann',
            name='tile',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
